#ProjectTitle
#Barangay_San_Isidro_Constriction_Projects_Index
#ProjectProponents
#Hisarza, Jayson Malbas
#Salubre, Jhon Mark Mingoy
#Villegas, Claire Napeñas

print("Barangay San Isidro Construction Project Index")
print()
print()
print("PRESS '1' to Proceed to View the Informations")
print("PRESS '0' to Quit")
print()

option = int(input("Kindly Choose:"))
print()
while option != 0:
	if option == 1:
		print("1. Rehabilitation of Covered Court")
		print("2. Concreting of 0.345 km Barangay Road")
		print("3. Relocation of Barangay Hall")
		print("4. 88.473 meters Dike Construction")
		print("5. Sewage Concrete Reinforcement within PUROK 1")
		print("6. 10x10x4.5 meters Day-care Center")
		print("7. QUIT")
		print()
		choice = int(input("What Construction Project do you want to know:"))
		print()
		print()
		pass
		if choice == 1:
				print("Name of Project: Rehabilitation of Covered Court")
				print()
				print("Contractor: Barangay Officials")
				print()
				print("Project Workers: Local Workers")
				print()
				print("Total Budget: 369,741 pesos")
				print()
				print("LGU Contribution: 5,500 pesos")
				print()
				print("Project Duration: 24 Calendar Days")
				print()
				print("Project Date Completion: July 04, 2015")
				print()
				print("Purpose of Project: It was decided by the LGU and Barangay Officials. The covered court was rehabilitated for the locals to have not undergo difficulities during barangay festivities and events. It was also rehabilitated to prevent the future deathly risks that may happens.")
				print()
				print()
		elif choice == 2:
			print("Name of Project: Concreting of 1.345 km Barangay Road")
			print("Contractor: Barangay Officials")
			print()
			print("Project Workers: Local Workers")
			print()
			print("Total Budget: 1,408,514 pesos")
			print()
			print("LGU Contribution: 140,851 pesos")
			print()
			print("Project Duration: 38 Calendar Days")
			print()
			print("Project Date Completion: July 04, 2013")
			print()
			print("Purpose of Project: The projects was implemented to provide an easy transport of local citizens on this very mountainous area. It helps the local citizens and travelers to have an easy access going inside this barangay. This also helps the travelers to have a smooth travel while passing on our barangay.")
			print()
			print()
		elif choice == 3:
			print("Name of Project: Relocation of Barangay Hall")
			print("Contractor: Barangay Officials")
			print()
			print("Project Workers: Local Workers")
			print()
			print("Total Budget: 1,657,700 pesos")
			print()
			print("LGU Contribution: 115,690 pesos")
			print()
			print("Project Duration: 61 Calendar Days")
			print()
			print("Project Date Completion: March 07, 2018")
			print()
			print("Purpose of Project: Since,barangay hall is the seat of government for a barangay. It is much preferable if it is near the open area to become more accessible. The reason of the rellocation is to broadcast to citizens that 'we have a hall, you can call for help'. The purpose is to become a more lively barangay that more accessible to its local citizens.")
			print()
			print()
		elif choice == 4:
			print("Name of Project: 88.473 meters Dike Construction")
			print("Contractor: Blue Sapphire Corp")
			print()
			print("Project Workers: Blue Sapphire Workers")
			print()
			print("Total Budget: 989,670.15 pesos")
			print()
			print("LGU Contribution: 245,000 pesos")
			print()
			print("Project Duration: 20 Calendar Days")
			print()
			print("Project Date Completion: June 7, 2018")
			print()
			print("Purpose of Project: The purpose of the project is to secure the safety of the Barangay from the possible risks of floods. The dike was constructed to prevent the river water to flow throughout the barangay during calamities like tropical storms.")
			print()
			print()
		elif choice == 5:
			print("Name of Project: Sewage Concrete Reinforcement within PUROK 1")
			print("Contractor: Barangay Officials")
			print()
			print("Project Workers: Barangay Workers")
			print()
			print("Total Budget: 297,090 pesos")
			print()
			print("LGU Contribution: 10,690")
			print()
			print("Project Duration: 16 Calendar Days")
			print()
			print("Project Date Completion: March 16, 2017")
			print()
			print("Purpose of Project: At year 2016 there is an abrupt rising of DENGUE fever throughout the Locality. To prevent it from happening again the barangay officials propose this project since mosquitoes lay and live on the sewages and unhealthy areas. Purok 1 is the place choosen because it is where the first case happen and since purok 2 and 3 had no large sewage system because houses are far apart from each other.")
			print()
			print()
		elif choice == 6:
			print("Name of Project: 10x10x4.5 meters Day-care Center")
			print("Contractor: Engr. Wales")
			print()
			print("Project Workers: Municipal Construction Workers")
			print()
			print("Total Budget: 1,568,357.89 pesos")
			print()
			print("LGU Contribution: 578,300 pesos")
			print()
			print("Project Duration: 57 Calendar Days")
			print()
			print("Project Date Completion: February 20, 2008")
			print()
			print("Purpose of Project: Day care center was constructed to help the local youngsters on their journey in life. Day care center is the place where they start to enhance their knowledge and skills as a future assests of the community.")
			print()
			print()
		else:
			print("Thank You for Accessing! Hope I provided your needed information")
			break
else:
	print("Thank You for Accessing! Hope I provided your needed information")